USE [enter_db_name_here]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[RSCHED_CUSTOM_JOBS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [dbo].[RSCHED_CUSTOM_JOBS]
GO

CREATE TABLE [dbo].[RSCHED_CUSTOM_JOBS] (
  [ID] [uniqueidentifier] NOT NULL ,
  [NAME] [NVARCHAR] (100)  NOT NULL ,
  [PARAMS] [NVARCHAR] (MAX)  NULL ,
  [JOB_TYPE] [NVARCHAR] (200)  NOT NULL
)
GO
